# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OusIO6bMrtuRR-evZwHkqfYB3-HLIEPd
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile our_application.py
# import streamlit as st
# st.write("hello")

! wget -q -O - ipv4.icanhazip.com

! streamlit run our_application.py & npx localtunnel --port 8501