# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OusIO6bMrtuRR-evZwHkqfYB3-HLIEPd
"""

pip install streamlit


! wget -q -O - ipv4.icanhazip.com

! streamlit run our_application.py & npx localtunnel --port 8501
