# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OusIO6bMrtuRR-evZwHkqfYB3-HLIEPd
"""

import streamlit as st
st.write("hello")
